set ND_HOME=c:\osullivj\src\nodom
set ND_EMS_HOME=c:\osullivj\bld\emsdk
set "ND_MSVC_HOME=C:\Program Files\Microsoft Visual Studio\2022\Community"
set ND_PY_HOME=C:\osullivj\bin\py3.12.3x64
set ND_WABT_HOME=C:\osullivj\bld\wabt\bin
set ND_GNU_HOME=c:\ProgramData\chocolatey\bin
set ND_BOOST_HOME=c:\osullivj\bld\boost_1_79_0
set ND_SSL_HOME=c:\osullivj\bld\openssl-3.5.3
set ND_DUCK_HOME=c:\osullivj\bld\duckdb140
set ND_DUCK_ESM=https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@latest/+esm
