# std pkg
import asyncio
import functools
import json
import logging
import os.path
import random
import time

# nodom
import nd_consts
import nd_utils
import nd_web

# 3rd pty
import tornado
import tornado.websocket
from tornado.ioloop import IOLoop

# slimgui for the convenience of autogenerated table/window flag enums only
# we don't invoke any imgui behaviour here on the server side
# https://nurpax.github.io/slimgui/#enum-reference
from slimgui.imgui import ChildFlags, ComboFlags, TableFlags, WindowFlags
from tornado.options import define, options, parse_command_line

# default to 8890 for http. Override to 443 for https
# Tiingo auth_key key provided on the cmd line so we don't hardwire anywhere
define("port", default=8890, help="run on the given port", type=int)
define("auth", default="", help="Tiingo auth key", type=str)
define("turl", default="wss://api.tiingo.com/iex", help="Tiingo API URL", type=str)
define("emu",  default=False, help="Emulate Tiingo mkt data", type=bool)

NDAPP = "fin_server"

logr = nd_utils.init_logging(NDAPP, console=True)

FIN_LAYOUT = [
    dict(
        rname="Home",
        cspec=dict(
            title="NoDOM Trader",
            title_font="Arial"
        ),
        children=[
            dict(rname="PushFont", cspec=dict(font="CourierNew")),
            dict(rname="BeginChild",
                cspec=dict(
                    height=200,
                    title='InstrumentsParent'
                )
            ),
            dict(
                rname="Table",
                cspec=dict(
                    title="Instruments",
                    query_id="query_inst_tbl_qid",
                    menupop="instruments_rclick_menupop",
                    table_flags=TableFlags.SCROLL_Y
                    | TableFlags.ROW_BG
                    | TableFlags.BORDERS_OUTER
                    | TableFlags.BORDERS_V
                    | TableFlags.RESIZABLE
                    | TableFlags.HIDEABLE
                    | TableFlags.CONTEXT_MENU_IN_BODY
                ),
            ),
            dict(rname="EndChild"),
            dict(rname="Separator", cspec=dict()),
            dict(rname="BeginChild",
                cspec=dict(
                    height=200,
                    title='MarketParent'
                )
            ),
            dict(
                rname="LiveTable",
                cspec=dict(
                    title="Market data",
                    cname="tickers",
                    formats="formats",
                    buffer_size=256,
                    line_height=8,
                    table_flags=TableFlags.SCROLL_Y
                    | TableFlags.ROW_BG
                    | TableFlags.BORDERS_OUTER
                    | TableFlags.BORDERS_V
                    | TableFlags.RESIZABLE
                    | TableFlags.HIDEABLE
                    | TableFlags.CONTEXT_MENU_IN_BODY
                ),
            ),
            dict(rname="EndChild"),
            dict(rname="Separator", cspec=dict()),
            dict(rname="PopFont"),
            dict(rname="PushFont", cspec=dict(font="Arial", font_size=8)),
            dict(
                rname="Footer",
                cspec=dict(
                    db=True,
                    fps=True,
                    demo=True,
                    font_scale=True,
                    style=True,
                ),
            ),
            dict(rname="Spacing", cspec=dict()),
            dict(rname="DebugFooter", cspec=dict()),
            dict(rname="PopFont"),
        ],
    ),
    dict(
        widget_id="instrument_loading_modal",
        rname="LoadingModal",
        cspec=dict(
            title="Loading NoDOM Trader",
            title_font="Arial",
            body_font="CourierNew",
            cname="loading_instruments_message",
            spinner_radius=20,
            spinner_thickness=4,
        ),
    ),
]

# NB this is re-runnable script
REBLD_INST_TBL_SQL = """BEGIN;
DROP TABLE IF EXISTS instrument;
CREATE TABLE instrument as select * from read_parquet('https://localhost:443/api/parquet/iex_instruments.parquet');
COMMIT;"""
# action to raise loading modal, send SQL to rebuild instrument table to DuckDB
REBLD_INST_TBL_ACTN = {
    "ui_push":"instrument_loading_modal",
    "action":"Command",
    "query_id":"rebld_inst_tbl_qid",
    "cname":"rebld_inst_tbl_ckey"
}

QUERY_INST_TBL_SQL = "select * from instrument;"
# raise loading modal, send SQL request to DuckDB
QUERY_INST_TBL_ACTN = {
    "ui_pop":"LoadingModal",
    "action":"Query",
    "query_id":"query_inst_tbl_qid",
    "cname":"query_inst_tbl_ckey"
}

BATCH_INST_TBL_ACTN = {
    "action":"BatchRequest",
    "query_id":"query_inst_tbl_qid"
}

INIT_SUB_REQ_ACTN = {
    "action":"LiveRequest",
    "cname":"tickers"
}


FIN_DATA = {
    "rebld_inst_tbl_ckey":REBLD_INST_TBL_SQL,
    "query_inst_tbl_ckey":QUERY_INST_TBL_SQL,
    "tickers":["spy", "vym", "spwr", "chpt", "aren", "tanh",
                    "rare", "dell", "curr", "dlll", "alms", "mgn"],
    # fmtlib for the live fields ticker,timestamp,mid
    "formats":["{}","{}","{:>6.2f}"],
    "loading_instruments_message":["Loading IEX instruments..."],
    "actions":{
        # GUI.CacheLoaded on BB, DuckDB.Online for wasm
        # TODO: gate implementation
        "GUI.CacheLoaded":[REBLD_INST_TBL_ACTN, QUERY_INST_TBL_ACTN,
                            BATCH_INST_TBL_ACTN, INIT_SUB_REQ_ACTN]
    },
    "menus": {
        "instruments_rclick_menupop":["Subscribe"]
    }
}

EMU_TIINGO_SUB_RESPONSE = {
    "messageType":"I",
    "data": {
        "subscriptionId":13706
    },
    "response": {
        "code":200,
        "message":"Success"
    }
}

class FinService(nd_utils.Service):
    # invoke base ctor and pass True for is_duck_app
    def __init__(self, app_name, layout, data):
        super().__init__(app_name, layout, data, True)
        self.client_websocks = dict()
        self.pending_subs = []
        self.tiingo_websock = None
        self.emu_tickers = dict()

    def on_ws_open(self, ws):
        self.client_websocks[ws._uuid] = ws

    def on_ws_close(self, ws):
        self.client_websocks.pop(ws._uuid)

    async def connect_websock(self):
        if not options.emu:
            self.tiingo_websock = await tornado.websocket.websocket_connect(options.turl,
                                                    on_message_callback=self.on_tiingo)

    def on_live_request(self, client_uuid, msg_dict):
        self.client_uuid = client_uuid
        # msg_dict will look like...
        # nd_type:LiveRequest
        # tickers:['spy','vym']
        # thresholdLevel: 6:mid, 0 or 5 for TOB
        sub_dict = dict(
            eventName='subscribe',
            authorization=options.auth,
            eventData=dict(thresholdLevel=6, tickers=msg_dict['tickers'])
        )
        if not options.emu:
            self.tiingo_websock.write_message(json.dumps(sub_dict))
        else:
            callback = functools.partial(self.on_tiingo, msg=json.dumps(EMU_TIINGO_SUB_RESPONSE))
            IOLoop.current().call_later(2, callback)
        self.pending_subs.insert(0, msg_dict['tickers'])
        return []

    def on_tiingo(self, msg):
        # we're invoked directly by the tiingo websock, so msg is str
        # first figure out msg type I, H or A
        if not msg:
            self.tiingo_websock = None
            return
        update_s = None
        msg_dict = json.loads(msg)
        msg_type = msg_dict['messageType']
        if msg_type == 'H':
            logr.info(f"on_tiingo: HB {msg}")
            return
        if msg_type == 'I':
            if len(self.pending_subs) == 0:
                logr.error(f"on_tiingo: I no pending subs {msg}")
                return
            ticker_list = self.pending_subs.pop()
            update_s = json.dumps({"nd_type":'LiveResponse', "tickers":ticker_list})
            if options.emu:
                for tkr in ticker_list:
                    self.emu_tickers[tkr] = 100.0
                asyncio.get_running_loop().call_later(2, self.fake_mkt_data)
        elif msg_type == 'A':
            data_list = msg_dict['data']
            update_s = json.dumps({
                "nd_type":'LiveUpdate',
                "timestamp":data_list[0],
                "ticker":data_list[1],
                "mid":data_list[2]
            })
        elif msg_type == 'E':
            if len(self.pending_subs) == 0:
                logr.error(f"on_tiingo: E no pending subs {msg}")
                return
            ticker_list = self.pending_subs.pop()
            resp_dict = msg_dict["response"]
            update_s = json.dumps({
                "nd_type":'LiveResponse',
                "tickers":ticker_list,
                "error":resp_dict["code"],
                "message":resp_dict["message"]
            })
        for ws in self.client_websocks.values():
            ws.write_message(update_s)

    def fake_mkt_data(self):
        for ticker, price in self.emu_tickers.items():
            update_s = json.dumps({
                "nd_type":'LiveUpdate',
                "timestamp":time.time_ns(),
                "ticker":ticker,
                "mid":price
            })
            for ws in self.client_websocks.values():
                ws.write_message(update_s)
                logr.info(f"fake_mkt_data: {update_s}")
        for tkr in self.emu_tickers.keys():
            price = self.emu_tickers[tkr]
            self.emu_tickers[tkr] = price + (0.25 * random.choice([-1.0, 1.0]))
        asyncio.get_running_loop().call_later(2, self.fake_mkt_data)


# breadboard looks out for service at the module level
service = FinService(NDAPP, FIN_LAYOUT, FIN_DATA)

async def connect_tiingo(svc):
    while True:
        if not svc.tiingo_websock:
            await svc.connect_websock()
        await asyncio.sleep(3)

# wire up the PQ handler
EXTRA_HANDLERS = [
    (
        r"/api/parquet/(.*)",
        nd_web.ParquetHandler,
        dict(path=os.path.join(nd_consts.ND_ROOT_DIR, "dat")),
    )
]

async def http_main():
    app = nd_web.NDApp(service, EXTRA_HANDLERS)
    app.listen(options.port)
    logr.info(f"{NDAPP} port:{options.port}")
    if not options.emu:
        asyncio.ensure_future(connect_tiingo(service))
    await asyncio.Event().wait()


async def https_main():
    cert_path = os.path.normpath(os.path.join(nd_consts.ND_ROOT_DIR, "cfg"))
    app = nd_web.NDApp(service, EXTRA_HANDLERS)
    https_server = tornado.httpserver.HTTPServer(
        app,
        ssl_options={
            "certfile": os.path.join(cert_path, "ssl_cert.pem"),
            "keyfile": os.path.join(cert_path, "ssl_key.pem"),
        },
    )
    https_server.listen(options.port)
    logr.info(f"{NDAPP} port:{options.port} cert_path:{cert_path}")
    if not options.emu:
        asyncio.ensure_future(connect_tiingo(service))
    await asyncio.Event().wait()


if __name__ == "__main__":
    parse_command_line()
    if options.port == 443:
        asyncio.run(https_main())
    else:
        asyncio.run(http_main())
