# std pkg
import asyncio
import json
import logging
import os.path

# nodom
import nd_consts
import nd_utils
import nd_web

# 3rd pty
import tornado
import tornado.websocket

# slimgui for the convenience of autogenerated table/window flag enums only
# we don't invoke any imgui behaviour here on the server side
# https://nurpax.github.io/slimgui/#enum-reference
from slimgui.imgui import ChildFlags, ComboFlags, TableFlags, WindowFlags
from tornado.options import define, options, parse_command_line

# default to 8890 for http. Override to 443 for https
# Tiingo auth_key key provided on the cmd line so we don't hardwire anywhere
define("port", default=8890, help="run on the given port", type=int)
define("auth", default="", help="Tiingo auth key", type=str)
define("turl", default="wss://api.tiingo.com/iex", help="Tiingo API URL", type=str)

NDAPP = "fin_server"

logr = nd_utils.init_logging(NDAPP, console=True)

FIN_LAYOUT = [
    dict(
        rname="Home",
        cspec=dict(
            title="NoDOM Trader",
            title_font="Arial"
        ),
        children=[
            dict(rname="PushFont", cspec=dict(font="CourierNew")),
            dict(rname="BeginChild", cspec=dict(height=200)),
            dict(
                rname="Table",
                cspec=dict(
                    title="Instruments",
                    query_id="query_inst_tbl_qid",
                    menupop="instruments_rclick_menupop",
                    table_flags=TableFlags.SCROLL_Y
                    | TableFlags.ROW_BG
                    | TableFlags.BORDERS_OUTER
                    | TableFlags.BORDERS_V
                    | TableFlags.RESIZABLE
                    | TableFlags.HIDEABLE
                    | TableFlags.CONTEXT_MENU_IN_BODY
                ),
            ),
            dict(rname="EndChild"),
            dict(rname="Separator", cspec=dict()),
            dict(rname="PopFont"),
            dict(rname="PushFont", cspec=dict(font="Arial", font_size=8)),
            dict(
                rname="Footer",
                cspec=dict(
                    db=True,
                    fps=True,
                    demo=True,
                    font_scale=True,
                    style=True,
                ),
            ),
            dict(rname="Spacing", cspec=dict()),
            dict(rname="DebugFooter", cspec=dict()),
            dict(rname="PopFont"),
        ],
    ),
    dict(
        widget_id="instrument_loading_modal",
        rname="LoadingModal",
        cspec=dict(
            title="Loading NoDOM Trader",
            title_font="Arial",
            body_font="CourierNew",
            cname="loading_instruments_message",
            spinner_radius=20,
            spinner_thickness=4,
        ),
    ),
]

# NB this is re-runnable script
REBLD_INST_TBL_SQL = """BEGIN;
DROP TABLE IF EXISTS instrument;
CREATE TABLE instrument as select * from read_parquet('https://localhost:443/api/parquet/iex_instruments.parquet');
COMMIT;"""
# action to raise loading modal, send SQL to rebuild instrument table to DuckDB
REBLD_INST_TBL_ACTN = {
    "ui_push":"instrument_loading_modal",
    "action":"Command",
    "query_id":"rebld_inst_tbl_qid",
    "cname":"rebld_inst_tbl_ckey"
}

QUERY_INST_TBL_SQL = "select * from instrument;"
# raise loading modal, send SQL request to DuckDB
QUERY_INST_TBL_ACTN = {
    "ui_pop":"LoadingModal",
    "action":"Query",
    "query_id":"query_inst_tbl_qid",
    "cname":"query_inst_tbl_ckey"
}

BATCH_INST_TBL_ACTN = {
    "action":"BatchRequest",
    "query_id":"query_inst_tbl_qid"
}

INIT_SUB_REQ_ACTN = {
    "action":"LiveRequest",
    "cname":"tickers"
}


FIN_DATA = {
    "rebld_inst_tbl_ckey":REBLD_INST_TBL_SQL,
    "query_inst_tbl_ckey":QUERY_INST_TBL_SQL,
    "tickers":["spy", "vym"],
    "loading_instruments_message":["Loading IEX instruments..."],
    "actions":{
        # GUI.CacheLoaded on BB, DuckDB.Online for wasm
        # TODO: gate implementation
        "GUI.CacheLoaded":[REBLD_INST_TBL_ACTN, QUERY_INST_TBL_ACTN,
                            BATCH_INST_TBL_ACTN, INIT_SUB_REQ_ACTN]
    },
    "menus": {
        "instruments_rclick_menupop":["Subscribe"]
    }
}


class FinService(nd_utils.Service):
    # invoke base ctor and pass True for is_duck_app
    def __init__(self, app_name, layout, data):
        super().__init__(app_name, layout, data, True)

    async def connect_websock(self):
        self.tiingo_websock = await tornado.websocket.websocket_connect(options.turl,
            on_message_callback=self.on_tick)

    def on_live_request(self, client_uuid, msg_dict):
        # msg_dict will look like...
        # nd_type:LiveRequest
        # tickers:['spy','vym']
        sub_dict = dict(
            eventName='subscribe',
            authorization=options.auth,
            eventData=dict(thresholdLevel=5, tickers=msg_dict['tickers'])
        )
        self.tiingo_websock.write_message(json.dumps(sub_dict))
        return []

    def on_tick(self, msg):
        print(msg)


# breadboard looks out for service at the module level
service = FinService(NDAPP, FIN_LAYOUT, FIN_DATA)

# wire up the PQ handler
EXTRA_HANDLERS = [
    (
        r"/api/parquet/(.*)",
        nd_web.ParquetHandler,
        dict(path=os.path.join(nd_consts.ND_ROOT_DIR, "dat")),
    )
]

async def http_main():
    app = nd_web.NDApp(service, EXTRA_HANDLERS)
    app.listen(options.port)
    logr.info(f"{NDAPP} port:{options.port}")
    await service.connect_websock()
    await asyncio.Event().wait()


async def https_main():
    cert_path = os.path.normpath(os.path.join(nd_consts.ND_ROOT_DIR, "cfg"))
    app = nd_web.NDApp(service, EXTRA_HANDLERS)
    https_server = tornado.httpserver.HTTPServer(
        app,
        ssl_options={
            "certfile": os.path.join(cert_path, "ssl_cert.pem"),
            "keyfile": os.path.join(cert_path, "ssl_key.pem"),
        },
    )
    https_server.listen(options.port)
    logr.info(f"{NDAPP} port:{options.port} cert_path:{cert_path}")
    await service.connect_websock()
    await asyncio.Event().wait()


if __name__ == "__main__":
    parse_command_line()
    if options.port == 443:
        asyncio.run(https_main())
    else:
        asyncio.run(http_main())
