# std pkg
import asyncio
import json
import logging
import os.path

# nodom
import nd_consts
import nd_utils
import nd_web

# 3rd pty
import tornado

# slimgui for the convenience of autogenerated table/window flag enums only
# we don't invoke any imgui behaviour here on the server side
# https://nurpax.github.io/slimgui/#enum-reference
from slimgui.imgui import InputTextFlags, WindowFlags
from tornado.options import define, options, parse_command_line

NDAPP = "qed_server"

logr = nd_utils.init_logging(NDAPP, console=True)

ADDITION_LAYOUT = [
    dict(
        rname="Home",
        cspec=dict(
            title="Query Editor",
            title_font="Arial",
        ),
        children=[
            dict(rname="PushFont", cspec=dict(font="CourierNew")),
            dict(rname="InputDouble", cspec=dict(cname="dbl")),
            dict(rname="InputString", cspec=dict(cname="str",
                                                buffer_size=64)),
            dict(rname="Separator", cspec=dict()),
            dict(rname="PopFont"),
            dict(rname="PushFont", cspec=dict(font="Arial", font_size=8)),
            dict(
                rname="Footer",
                cspec=dict(
                    db=True,
                    fps=True,
                    demo=True,
                    id_stack=True,
                    memory=True,
                    font_scale=True,
                    style=True,
                    dlc=True,
                ),
            ),
            dict(rname="Spacing", cspec=dict()),
            dict(rname="DebugFooter",cspec=dict()),
            dict(rname="PopFont"),
        ],
    ),
    dict(
        widget_id="menu_modal",
        rname="LoadingModal",
        cspec=dict(
            title="Menu modal...",
            title_font="Arial",
            body_font="CourierNew",
            cname="loading_message",
            spinner_radius=20,
            spinner_thickness=4,
        ),
    ),
]


ADDITION_DATA = dict(
    dbl=0.1,
    str="Edit me please!",
    loading_message=["Loading..."],
)


class QueryEditService(nd_utils.Service):
    def on_client_data_change(self, uuid, client_change):
        logr.info(f"on_client_data_change:client:{uuid}, change:{client_change}")
        return []


# breadboard looks out for service at the module level
service = QueryEditService(NDAPP, ADDITION_LAYOUT, ADDITION_DATA)

# default to 8890 for http. Override to 443 for https
define("port", default=8890, help="run on the given port", type=int)


async def http_main():
    app = nd_web.NDApp(service)
    app.listen(options.port)
    logr.info(f"{NDAPP} port:{options.port}")
    await asyncio.Event().wait()


async def https_main():
    cert_path = os.path.normpath(os.path.join(nd_consts.ND_ROOT_DIR, "cfg"))
    app = nd_web.NDApp(service)
    https_server = tornado.httpserver.HTTPServer(
        app,
        ssl_options={
            "certfile": os.path.join(cert_path, "ssl_cert.pem"),
            "keyfile": os.path.join(cert_path, "ssl_key.pem"),
        },
    )
    https_server.listen(options.port)
    logr.info(f"{NDAPP} port:{options.port} cert_path:{cert_path}")
    await asyncio.Event().wait()


if __name__ == "__main__":
    parse_command_line()
    if options.port == 443:
        asyncio.run(https_main())
    else:
        asyncio.run(http_main())
